services:
  whoami:
    image: traefik/whoami
    networks:
      - caddy
    labels:
      caddy: whoami.henriquesf.me
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
