version: '3.8'

services:
  sharelatex:
    image: tuetenk0pp/sharelatex-full:latest
    container_name: sharelatex
    restart: always
    stop_grace_period: 60s
    networks:
      - caddy
    volumes:
      - /var/lib/sharelatex:/var/lib/overleaf
    labels:
      caddy: overleaf.henriquesf.me
      caddy.reverse_proxy: "{{upstreams 80}}" 
    environment:
      OVERLEAF_APP_NAME: "Overleaf Henrique"
      OVERLEAF_SITE_URL: "https://overleaf.henriquesf.me"
      OVERLEAF_BEHIND_PROXY: "true"
      OVERLEAF_ADMIN_EMAIL: "me@henriquesf.me"
      OVERLEAF_EMAIL_FROM_ADDRESS: "overleaf@henriquesf.me"
      OVERLEAF_MONGO_URL: "mongodb://mongo:27017/sharelatex"
      OVERLEAF_MONGO_REPLICA_SET: "overleaf"
      OVERLEAF_REDIS_HOST: "redis-overleaf"
      REDIS_HOST: "redis-overleaf"
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
      SANDBOXED_COMPILES: "false"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    command: ["--replSet", "overleaf"]
    volumes:
      - /var/lib/sharelatex/mongo:/data/db
      - ./mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: "sharelatex"
      GLIBC_TUNABLES: "glibc.pthread.rseq=1"
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2
    container_name: redis-overleaf
    restart: always
    volumes:
      - /var/lib/sharelatex/redis:/data

networks:
  caddy:
    external: true
