services:
  glances:
    container_name: glances
    image: nicolargo/glances:ubuntu-latest-full
    ports:
      - 61208:61208
      - 61209:61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    environment:
      - "GLANCES_OPT=-w"

networks:
  default:
    external: true
    name: npm
