services:
  registry:
    image: goharbor/registry-photon:v2.14.4
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/registry:/storage:z
      - /home/ricky/infra-deployments/services/harbor/common/config/registry/:/etc/registry/:z
      - type: bind
        source: /data/secret/registry/root.crt
        target: /etc/registry/root.crt
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
  registryctl:
    image: goharbor/harbor-registryctl:v2.14.4
    container_name: registryctl
    environment:
      CORE_SECRET: ${CORE_SECRET}
      JOBSERVICE_SECRET: ${JOBSERVICE_SECRET}
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/registry:/storage:z
      - /home/ricky/infra-deployments/services/harbor/common/config/registry/:/etc/registry/:z
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
  postgresql:
    image: goharbor/harbor-db:v2.14.4
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  core:
    image: goharbor/harbor-core:v2.14.4
    container_name: harbor-core
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      UAA_CA_ROOT: ${UAA_CA_ROOT}
      _REDIS_URL_CORE: ${_REDIS_URL_CORE}
      SYNC_QUOTA: ${SYNC_QUOTA}
      _REDIS_URL_REG: ${_REDIS_URL_REG}
      LOG_LEVEL: ${LOG_LEVEL}
      EXT_ENDPOINT: ${EXT_ENDPOINT}
      DATABASE_TYPE: ${DATABASE_TYPE}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_PORT: ${POSTGRESQL_PORT}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_SSLMODE: ${POSTGRESQL_SSLMODE}
      POSTGRESQL_MAX_IDLE_CONNS: ${POSTGRESQL_MAX_IDLE_CONNS}
      POSTGRESQL_MAX_OPEN_CONNS: ${POSTGRESQL_MAX_OPEN_CONNS}
      POSTGRESQL_CONN_MAX_LIFETIME: ${POSTGRESQL_CONN_MAX_LIFETIME}
      POSTGRESQL_CONN_MAX_IDLE_TIME: ${POSTGRESQL_CONN_MAX_IDLE_TIME}
      REGISTRY_URL: ${REGISTRY_URL}
      PORTAL_URL: ${PORTAL_URL}
      TOKEN_SERVICE_URL: ${TOKEN_SERVICE_URL}
      HARBOR_ADMIN_PASSWORD: ${HARBOR_ADMIN_PASSWORD}
      MAX_JOB_WORKERS: ${MAX_JOB_WORKERS}
      CORE_SECRET: ${CORE_SECRET}
      JOBSERVICE_SECRET: ${JOBSERVICE_SECRET}
      WITH_TRIVY: ${WITH_TRIVY}
      CORE_URL: ${CORE_URL}
      CORE_LOCAL_URL: ${CORE_LOCAL_URL}
      JOBSERVICE_URL: ${JOBSERVICE_URL}
      TRIVY_ADAPTER_URL: ${TRIVY_ADAPTER_URL}
      REGISTRY_STORAGE_PROVIDER_NAME: ${REGISTRY_STORAGE_PROVIDER_NAME}
      READ_ONLY: ${READ_ONLY}
      RELOAD_KEY: ${RELOAD_KEY}
      REGISTRY_CONTROLLER_URL: ${REGISTRY_CONTROLLER_URL}
      REGISTRY_CREDENTIAL_USERNAME: ${REGISTRY_CREDENTIAL_USERNAME}
      REGISTRY_CREDENTIAL_PASSWORD: ${REGISTRY_CREDENTIAL_PASSWORD}
      CSRF_KEY: ${CSRF_KEY}
      ROBOT_SCANNER_NAME_PREFIX: ${ROBOT_SCANNER_NAME_PREFIX}
      PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE: ${PERMITTED_REGISTRY_TYPES_FOR_PROXY_CACHE}
      REPLICATION_ADAPTER_WHITELIST: ${REPLICATION_ADAPTER_WHITELIST}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      PORT: ${PORT}
      QUOTA_UPDATE_PROVIDER: ${QUOTA_UPDATE_PROVIDER}
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /data/ca_download/:/etc/core/ca/:z
      - /data/:/data/:z
      - /home/ricky/infra-deployments/services/harbor/common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /data/secret/keys/secretkey
        target: /etc/core/key
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      harbor:
    depends_on:
      - registry
      - redis
      - postgresql
  portal:
    image: goharbor/harbor-portal:v2.14.4
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/portal/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - harbor

  jobservice:
    image: goharbor/harbor-jobservice:v2.14.4
    container_name: harbor-jobservice
    environment:
      CORE_SECRET: ${CORE_SECRET}
      REGISTRY_URL: ${REGISTRY_URL}
      JOBSERVICE_SECRET: ${JOBSERVICE_SECRET}
      CORE_URL: ${CORE_URL}
      REGISTRY_CONTROLLER_URL: ${REGISTRY_CONTROLLER_URL}
      JOBSERVICE_WEBHOOK_JOB_MAX_RETRY: ${JOBSERVICE_WEBHOOK_JOB_MAX_RETRY}
      JOBSERVICE_WEBHOOK_JOB_HTTP_CLIENT_TIMEOUT: ${JOBSERVICE_WEBHOOK_JOB_HTTP_CLIENT_TIMEOUT}
      LOG_LEVEL: ${LOG_LEVEL}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      REGISTRY_CREDENTIAL_USERNAME: ${REGISTRY_CREDENTIAL_USERNAME}
      REGISTRY_CREDENTIAL_PASSWORD: ${REGISTRY_CREDENTIAL_PASSWORD}
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
    depends_on:
      - core
  redis:
    image: goharbor/redis-photon:v2.14.4
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /data/redis:/var/lib/redis
    networks:
      harbor:
  proxy:
    image: goharbor/nginx-photon:v2.14.4
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - /home/ricky/infra-deployments/services/harbor/common/config/nginx:/etc/nginx:z
      - type: bind
        source: /home/ricky/infra-deployments/services/harbor/common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
      - caddy
    labels:
      caddy: harbor.henriquesf.me
      caddy.reverse_proxy: "{{upstreams 80}}"
    ports:
      - 80:80
    depends_on:
      - registry
      - core
      - portal
networks:
  harbor:
    external: false
  caddy:
    external: true
