#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$MASTER_USER" --dbname "$MASTER_DB" <<-EOSQL
    CREATE DATABASE "$IMPACT_SPHERE_DB_NAME";
    CREATE USER "$IMPACT_SPHERE_DB_USER" WITH ENCRYPTED PASSWORD '$IMPACT_SPHERE_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE "$IMPACT_SPHERE_DB_NAME" TO "$IMPACT_SPHERE_DB_USER";
EOSQL
