name: Deploy All Compose Services

on:
  push:
    branches:
      - main
    paths:
      - "compose/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Prepare SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      - name: Deploy all services
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          REPO_PATH: ${{ secrets.REPO_PATH }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST \
            REPO_PATH="$REPO_PATH" \
            bash << 'EOF'
          set -e
          cd "$REPO_PATH"
          
          git fetch origin main
          git reset --hard origin/main
          git pull
          
          ./deploy.sh
          EOF
