name: Deploy Changed Compose Services

on:
  push:
    branches:
      - main
    paths:
      - "compose/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Setup Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}

      - name: Prepare SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      - name: Detect changed compose folders
        id: changed
        run: |
          echo "Detecting changed folders..."
          changed_folders=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} | grep '^compose/' | awk -F/ '{print $2}' | sort -u)
          echo "Changed folders: $changed_folders"
          echo "folders=$changed_folders" >> $GITHUB_OUTPUT

      - name: Deploy changed services
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          for folder in ${{ steps.changed.outputs.folders }}; do
            if [ -f "compose/$folder/docker-compose.yml" ]; then
              echo "Deploying $folder..."
              ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST bash << 'EOF'
                set -e
                # Login to private registry
                docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" registry.henriquesf.me

                # Navigate to project folder on server
                cd /path/to/compose/$folder

                # Pull latest images and redeploy using Doppler
                doppler run -- docker compose pull
                doppler run -- docker compose up -d
EOF
            fi
          done

