name: Deploy All Compose Services

on:
  push:
    branches:
      - main
    paths:
      - "compose/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Setup Doppler CLI
        uses: dopplerhq/cli-action@v3
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}

      - name: Prepare SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      - name: Deploy all services
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          for folder in compose/*; do
            if [ -f "$folder/docker-compose.yml" ]; then
              echo "Deploying $folder..."
              ssh -i key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST bash << 'EOF'
                set -e
                FOLDER=$(basename "$folder")
                cd "$REPO_PATH/$FOLDER"

                git fetch origin main
                git reset --hard origin/main

                docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" registry.henriquesf.me

                doppler run -- docker compose pull
                doppler run -- docker compose up -d
              EOF
            fi
          done

