services:
  api:
    image: harbor.henriquesf.me/tennis/tennis-api:latest
    container_name: tennis-api
    restart: unless-stopped
    networks:
      - caddy
      - postgres_network
    labels:
      caddy: api.tennis.henriquesf.me
      caddy.reverse_proxy: "{{upstreams 3000}}"
    environment:
      - BETTER_AUTH_API_KEY=${BETTER_AUTH_API_KEY}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PORT=3000
  frontend:
    image: harbor.henriquesf.me/tennis/tennis-frontend:latest
    container_name: tennis-frontend
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: tennis.henriquesf.me
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  postgres_network:
    external: true
  caddy:
    external: true
